import type { GameItem, Machine, ShopInfo } from "../types";

export const VALID_SETUP_CODE = "WB-SHOP-4821";

export const shop: ShopInfo = {
  name: "Windhoek Central",
  location: "Independence Ave, Windhoek",
  tagline: "Independent. Fair. Reliable. Windhoek Central.",
};

export const machineConfig: { smartPc: Machine; terminal: Machine } = {
  smartPc: {
    name: "Smart PC-03",
    type: "smart-pc",
    balance: 250.00,
    shopName: shop.name,
    location: shop.location,
    action: "Cash Out",
  },
  terminal: {
    name: "Terminal-02",
    type: "terminal",
    balance: 100.00,
    shopName: shop.name,
    location: shop.location,
    action: "Print Cashout Ticket",
  },
};

export const games: GameItem[] = [
  {
    id: 1,
    name: "aviator",
    title: "AVIATOR",
    subtitle: "FLY HIGH • 10,000X MAX",
    category: "crash",
    categories: ["crash", "instant", "slots"],
    theme: "theme-red",
    badge: { text: "HOT", type: "hot", icon: "fa-solid fa-fire" },
    image: "/assets/games/1.png",
    actionText: "PLAY NOW",
  },
  {
    id: 2,
    name: "lucky dice",
    title: "LUCKY DICE",
    subtitle: "ROLL & WIN • 98.6% RTP",
    category: "table",
    categories: ["table", "instant", "live"],
    theme: "theme-purple",
    badge: { text: "TOP", type: "cyan", icon: "fa-solid fa-dice" },
    image: "/assets/games/2.png",
    actionText: "ROLL NOW",
  },
  {
    id: 3,
    name: "plinko vip",
    title: "PLINKO VIP",
    subtitle: "DROP BALL • 1,000X MULTI",
    category: "instant",
    categories: ["instant", "slots"],
    theme: "theme-magenta",
    badge: { text: "HOT", type: "hot", icon: "fa-solid fa-bullseye" },
    image: "/assets/games/3.png",
    actionText: "DROP NOW",
  },
  {
    id: 4,
    name: "cyber mines",
    title: "CYBER MINES",
    subtitle: "AVOID MINES • CASH OUT",
    category: "table",
    categories: ["instant", "table", "slots"],
    theme: "theme-green",
    badge: { text: "VIP", type: "green", icon: "fa-solid fa-shield-halved" },
    image: "/assets/games/4.png",
    actionText: "PLAY NOW",
  },
  {
    id: 5,
    name: "penalty goal",
    title: "PENALTY GOAL",
    subtitle: "SCORE BIG • 97.8% RTP",
    category: "sports",
    categories: ["sports", "live", "instant"],
    theme: "theme-blue",
    badge: { text: "POPULAR", type: "cyan", icon: "fa-solid fa-futbol" },
    image: "/assets/games/5.png",
    actionText: "KICK NOW",
  },
  {
    id: 6,
    name: "rocket crash",
    title: "ROCKET CRASH",
    subtitle: "FLY HIGH • 5,000X MAX",
    category: "crash",
    categories: ["crash", "instant", "slots"],
    theme: "theme-gold",
    badge: { text: "5000X", type: "gold", icon: "fa-solid fa-bolt" },
    image: "/assets/games/6.png",
    actionText: "LAUNCH",
  },
  {
    id: 7,
    name: "jet flight",
    title: "JET FLIGHT",
    subtitle: "TURBO FLY • MULTIPLIER",
    category: "crash",
    categories: ["crash", "live", "instant"],
    theme: "theme-blue",
    badge: { text: "FAST", type: "cyan", icon: "fa-solid fa-plane-departure" },
    image: "/assets/games/avi.png",
    actionText: "FLY NOW",
  },
  {
    id: 8,
    name: "crazy crash",
    title: "CRAZY CRASH",
    subtitle: "MULTIPLAYER • LIVE ACTION",
    category: "crash",
    categories: ["crash", "live", "table"],
    theme: "theme-red",
    badge: { text: "LIVE", type: "live", icon: "fa-solid fa-circle" },
    image: "/assets/games/1.png",
    actionText: "JOIN ROOM",
  },
  {
    id: 9,
    name: "gates of olympus",
    title: "OLYMPUS BLITZ",
    subtitle: "GATES OF ZEUS • 5,000X",
    category: "slots",
    categories: ["slots"],
    theme: "theme-gold",
    badge: { text: "500X", type: "gold", icon: "fa-solid fa-bolt" },
    image: "/assets/games/3.png",
    actionText: "SPIN NOW",
  },
  {
    id: 10,
    name: "sweet bonanza",
    title: "SWEET BONANZA",
    subtitle: "TUMBLE REELS • 100X MULTI",
    category: "slots",
    categories: ["slots"],
    theme: "theme-magenta",
    badge: { text: "BONUS", type: "hot", icon: "fa-solid fa-fire" },
    image: "/assets/games/2.png",
    actionText: "SPIN NOW",
  },
  {
    id: 11,
    name: "sugar rush",
    title: "SUGAR RUSH",
    subtitle: "MULTIPLIER SPOTS • 128X",
    category: "slots",
    categories: ["slots", "instant"],
    theme: "theme-purple",
    badge: { text: "NEW", type: "cyan", icon: "fa-solid fa-star" },
    image: "/assets/games/4.png",
    actionText: "SPIN NOW",
  },
  {
    id: 12,
    name: "live roulette",
    title: "LIVE ROULETTE",
    subtitle: "EUROPEAN • 36 NUMBERS",
    category: "live",
    categories: ["table", "live"],
    theme: "theme-red",
    badge: { text: "LIVE", type: "live", icon: "fa-solid fa-circle" },
    image: "/assets/games/5.png",
    actionText: "BET NOW",
  },
  {
    id: 13,
    name: "blackjack pro",
    title: "BLACKJACK PRO",
    subtitle: "PERFECT PAIRS • 3:2 PAY",
    category: "table",
    categories: ["table", "live"],
    theme: "theme-green",
    badge: { text: "VIP", type: "green", icon: "fa-solid fa-shield-halved" },
    image: "/assets/games/6.png",
    actionText: "DEAL NOW",
  },
  {
    id: 14,
    name: "live baccarat",
    title: "LIVE BACCARAT",
    subtitle: "SPEED BACCARAT • NO COMM",
    category: "live",
    categories: ["table", "live"],
    theme: "theme-purple",
    badge: { text: "LIVE", type: "cyan", icon: "fa-solid fa-user-tie" },
    image: "/assets/games/2.png",
    actionText: "BET NOW",
  },
  {
    id: 15,
    name: "virtual sports",
    title: "VIRTUAL LEAGUE",
    subtitle: "3-MIN MATCHES • LIVE ODDS",
    category: "sports",
    categories: ["sports"],
    theme: "theme-blue",
    badge: { text: "24/7", type: "cyan", icon: "fa-solid fa-futbol" },
    image: "/assets/games/5.png",
    actionText: "BET NOW",
  },
  {
    id: 16,
    name: "crash royale",
    title: "CRASH ROYALE",
    subtitle: "118.5K PLAYERS • ROOM",
    category: "crash",
    categories: ["crash", "live"],
    theme: "theme-red",
    badge: { text: "24/7", type: "hot", icon: "fa-solid fa-fire" },
    image: "/assets/games/1.png",
    actionText: "JOIN ROOM",
  },
];
